# Generated by Django 3.2.5 on 2021-08-26 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210825_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='room_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ManyToManyField(to='chat.Room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 26, 14, 45, 26, 576558)),
        ),
    ]
