# Generated by Django 3.2.5 on 2021-08-26 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210826_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 26, 20, 29, 47, 5711)),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=100000),
        ),
    ]
