# Generated by Django 3.2.5 on 2021-08-26 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 26, 20, 53, 54, 261586)),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=1000000),
        ),
    ]
